//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> isDisplay { get; set; }
        public Nullable<int> idType { get; set; }
    
        public virtual TypeNew TypeNew { get; set; }
    }
}
